# Generated by Django 4.0.5 on 2022-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='iso',
            field=models.CharField(help_text='ISO', max_length=3, verbose_name='ISO (Alpha-2 code)'),
        ),
    ]
